### ISSUE TITLE
web-ish authenticating with toggl

### ISSUE THREAD

**Issue by abloch** [toggl/toggl_api_docs#109]
Hi!

I want to create a web-based service that interacts with toggl (I want to measure the work done with it).
the problem is that there's no way for me to get the user's token without referring him/her to https://www.toggl.com/api/v8/me and then asking them to copy paste the token).
there should be an authomatic way to authentication a user facebook/google/twitter/github have

thanks

**Comment by oshev** [comment]
To be honest, I don't see how asking users to provide their login/password is better than directly asking for their API Token. It's certainly less secure and seems more suspicious from user's point of view. Maybe it's a bit simpler for non-technical users but it doesn't really eliminate the original need of a better authentication for web-based services querying Toggl. It's been 2.5 years ago, you discussed this, I wonder if something has changed since then and Toggl developers are more open implementing this feature.

**Comment by nickelbob** [comment]
Hi Toggl! Love the service but really interested in building some integrations with it. Unfortunately no oauth support means either not integrating OR doing it in an insecure way... any news on this front. Loving the product otherwise!
