### ISSUE TITLE
Add support to filter data by timestamps

### ISSUE THREAD

**Issue by joaodiogocosta** [toggl/toggl_api_docs#126]
It woud be great to have support to filter data by timestamp.

Right now (in v8), only the endpoint to retrieve `user data` and the endpoint to retrieve `time entries` has support for this. This would be helpful to optimize our queries in the client side, and also for Toggl in the server side.

As an example, I would like to be able to do something like this:

``` 
https://www.toggl.com/api/v8/workspaces?since=1420070400
```

Or

```
https://www.toggl.com/api/v8/workspaces/xxx/projects?since=1420070400
```

Thanks!

**Comment by zveroboyisme** [comment]
It would also be great if in general client can retrieve a list of ids of the entities which changed since provided time.  This will further reduce the load on the toggl servers and make client, which cache data, more responsive.  What does everyone think about that?

**Comment by refiito** [comment]
The upcoming API version (v9) will have the since parameter for pretty much every request.

The changed ID-s... well, the id list would most likely not help when trying to keep data in sync - OK, you get the changed object ID-s, but what changed still requires a request (eg. 10 objects change, one is doing 11 requests - one for changed id-s and 10 for new objects).

I'm leaving the issue open for now... since it seems people have thoughts and ideas.

**Comment by joaodiogocosta** [comment]
@refiito thanks. Is there any change of v8 still get the "since" parameter? Also, is there an estimated release date for v9?

**Comment by refiito** [comment]
@joaodiogocosta for v8 there are currently no plans to do this.

For the v9 - a few endpoints are already up and running (hint: you may use the browser console to trace what is already up and used), however there is no public documentation yet, but we'll start adding it shortly (with the note that some endpoints and structures may change).

**Comment by joaodiogocosta** [comment]
@refiito thanks!
