### ISSUE TITLE
Detailed reports since-until range query returns out of range result

### ISSUE THREAD

**Issue by alexattws** [toggl/toggl_api_docs#149]
When I send the following request,

curl -v -u ***redacted***:api_token -H "Content-Type: application/json" -X GET "https://www.toggl.com/reports/api/v2/details?since=2015-07-12T07%3A00%3A00%2B0000&until=2015-07-19T06%3A59%3A59%2B0000&page=1&user_agent=alex%40totalwebservices.net&workspace_id=42362"

I get the following record,

{"id":255624470, ....... ,"description":"test","start":"2015-07-19T11:03:00-07:00","end":"2015-07-19T11:04:04-07:00","updated":"2015-07-27T17:07:32-07:00","dur":64000, .......}

Notice the start and end date are around 2015-07-19 11 AM PDT which is 6 PM UTC.
The query since-until parameters are 2015-07-12 07:00:00 UTC - 2015-07-19 06:59:59 UTC.

The result returned by the API is out of bounds.

**Comment by seanculver** [comment]
@alexattws I was having the same issue and soon realized that the `since` and `until` request params are simple dates, and ignore any time specified.

https://github.com/toggl/toggl_api_docs/blob/master/reports.md#request-parameters

If I understand correctly using the detailed report is the only way to get time entries that were not created by you. 

+1 for time support for `since` and `until`

**Comment by webervin** [comment]
@seanculver is correct - since and until work according to specification. We will consider adding stricter validation of YYYY-MM-DD format not having anything extra at the end.

PS for 'other way to get time entries that where not created by you' take a look on [pipes](https://github.com/toggl/pipes-api) + [UI](https://github.com/toggl/pipes-ui)

**Comment by alexattws** [comment]
Here is the issue, there is no way to communicate the time zone with YYYY-MM-DD.  So, I assume it is a specific time zone.  What time zone are we talking about?  UTC?  Server time zone?  API token user time zone?

It is rather limiting that you cannot specify time as well as the time zone in these fields.  Makes them almost useless, really.

**Comment by webervin** [comment]
we are talking about each user's own time zone, as is set currently in profile for each user in workspace at time of request.

**Comment by alexattws** [comment]
This is very inconvenient.  If the desired timezone for a query differs from the user timezone, these fields are almost useless.
