### ISSUE TITLE
Support for time in since and until for the reports api

### ISSUE THREAD

**Issue by seanculver** [toggl/toggl_api_docs#182]
First of all, thanks for making my life easier by building out this API. 

It seems I'm not the only person who was confused by not being able to get reports for a particular time period.

https://github.com/toggl/toggl_api_docs/issues/149
https://github.com/toggl/toggl_api_docs/issues/170
https://github.com/toggl/toggl_api_docs/issues/177
https://github.com/toggl/toggl_api_docs/issues/147

The problem arises because `since` and `until` are[ ignoring time](https://github.com/toggl/toggl_api_docs/blob/master/reports.md#request-parameters). As a user of the API this is not the expected behavior. Also, it seems like ISO 8601 supports time but documentation only has a date.

A couple questions. How does this work with Timezones? 

`since: '2016-06-01' is based on UTC (server time)?

I would propose you use ISO 8601 date and time format (YYYY-MM-DDTHH:MM:SS) for both `until` and `since`. As far as I know ISO 8601 can handle timezones.

Thanks for your consideration. I look forward to hearing what you have to say about the idea.

One last thing, maybe it does support time and I'm just crazy, I'd love to know that too!

**Comment by webervin** [comment]
Hello, 
as workspace may have users in different time zones since and until are dealing with each user local  timezone, taking time entries beginning from midnight  of since date  at each user's currently configured time zone.

As for support for times, expected behaviour is to behave according to published api [specification](https://github.com/toggl/toggl_api_docs/blob/master/reports.md):

```
since: string, ISO 8601 date (YYYY-MM-DD), by default until - 6 days.
until: string, ISO 8601 date (YYYY-MM-DD), by default today
```
 At design of reports api v2 we had no use cases where users would need sub-day reporting, you are welcome to provide use cases to be considered in future api implementations. Current reports api version 2 is considered stable and will not change it's behaviour.
