### ISSUE TITLE
Reports - consistent error, missing user_agent

### ISSUE THREAD

**Issue by jasonthane** [toggl/toggl_api_docs#209]
I believe there's a bug that is blocking all use of the reports API. No matter how I craft the request in curl, I get the following error:

Required parameter 'user_agent' is missing from request

Here are some of the commands I've tried - all produce this message:

curl -v -u (redacted_token):api_token -X GET https://toggl.com/reports/api/v2/summary?&workspace_id=1500740&since=2016-01-01&until=2016-12-31&user_agent=jason@generalui.com

curl -v -u (redacted_token):api_token -X GET https://toggl.com/reports/api/v2/summary?&workspace_id=1500740&user_agent=jason@generalui.com&since=2016-01-01&until=2016-12-31

curl -v -A "jason@generalui.com" -u (redacted_token):api_token -X GET https://toggl.com/reports/api/v2/summary?&workspace_id=1500740&user_agent=jason@generalui.com&since=2016-01-01&until=2016-12-31

**Comment by refiito** [comment]
Most likely you're missing quotes around the link, and & gets translated to the bash ampersand and that basically forks the process at first URI parameter

hence, pease run 
`curl -v -u (redacted_token):api_token -X GET "https://toggl.com/reports/api/v2/summary?&workspace_id=1500740&since=2016-01-01&until=2016-12-31&user_agent=jason@generalui.com"`
(note the quoting)
