### ISSUE TITLE
Creating Test Credentials for TDD testing

### ISSUE THREAD

**Issue by grantkemp** [toggl/toggl_api_docs#218]
It would be great if we can automate our tests using the API so would be useful to have a generic demo account which will respond to api requests correctly.

**Comment by kanet77** [comment]
I agree. I requested this feature from Toggl about a year ago. They said they were considering it:

> Thanks so much for reaching out! I've checked with our developers and we don't have anything in the works at the moment, however it is on our radar and we are looking into possible solutions for the future.

To test PRO features I used my own account. This made it difficult to manage real data and test data, especially because I want my integration tests to clean up generated test data without affecting real data. I created a second account to test free features only.

I canceled my PRO account because I stopped needing it. Now I have no way to test PRO features for my [togglv8](https://github.com/kanet77/togglv8) Ruby wrapper. Even when I was using my own PRO account, I couldn't find a way to [test CRUD operations on project users](https://coveralls.io/builds/7160971/source?filename=lib%2Ftogglv8%2Fproject_users.rb).
