### ISSUE TITLE
"Project tasks" responds null

### ISSUE THREAD

**Issue by rockymanobi** [toggl/toggl_api_docs#252]
I tried to get  [Project tasks](https://github.com/toggl/toggl_api_docs/blob/master/chapters/projects.md) but I continuously getting `null` as a response.

```bash
curl -u {$token}:api_token \
	-X GET https://www.toggl.com/api/v8/projects/{$project_id which is on  enterprise plan workspace}/tasks
```

Also, I fond a caution about this API ...

> Available only for pro workspaces

I'm not sure but it looks like , it's based on old Price Plan of Toggle , and this means Starter or Standard or Enterprise Plan.

**Comment by soylentgreeen202** [comment]
I'm also having this problem but also for workspace tasks.

**Comment by kadrihvl** [comment]
As Tasks are always specific to a Project, you'd indeed have to use the project_id parameter. So the curl does look legit... Now the question is - does the user who's making this request have access to this project (even if it's a Workspace admin, he'd have to be part of project's team in order to have access in case it's a 'private' project). We could investigate if we'd know the Workspace and project IDs.

**Comment by joeriharleman** [comment]
Hello @rockymanobi!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
