### ISSUE TITLE
How can I create a project that is set to "Anyone" or that anyone can see?

### ISSUE THREAD

**Issue by zbriggs** [toggl/toggl_api_docs#256]
I am writing an integration between Toggl and a task management system. How can I create a project that is set to "Anyone" or that anyone can see? It appears that I can only assign it to the user that is associated with the API key.

Zach

**Comment by brieuclambert** [comment]
The only way I found is to make a projects_users post request. You can add multiple users in one request, I add all my users this way (got the list from another request : `https://www.toggl.com/api/v8/workspaces/{workspace_id}/users` , right after creating a project. 
Hope it helps.

Brieuc

**Comment by zimmerel** [comment]
I know this is a little old and I'm not sure if it has been updated since you wrote this, but I just wrote a looping function to run through all my projects and set is_private to false. All projects have is_private set to true by default, which means only the creator and admins can see them.

You should be able to specify that property during the project creation and everyone would be able to see them.

Here is my data field: {"project": {"is_private": False}}

**Comment by joeriharleman** [comment]
Hello @zbriggs!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
