### ISSUE TITLE
No way to get list of all tags

### ISSUE THREAD

**Issue by samuelkordik** [toggl/toggl_api_docs#265]
There does not seem to be a way to get all tags (something like a GET request to https://www.toggl.com/api/v8/tags) and no way to delete tags by name. There's also no way to get tag ids when getting specific time entries.

**Comment by zimmerel** [comment]
I'm not sure in how exactly you are utilizing the API calls (URL calls or programmatically), but I just wanted to shed some light on how I handle the above mentioned:

There is a call in the workspaces section that can look for all tags in a given workspace that returns with their name, ID and the workspace ID. If you are using multiple workspaces, you can use the get workspaces call and then loop through them, passing each ID as the parameter to get the tags for that workspace.

https://github.com/toggl/toggl_api_docs/blob/master/chapters/workspaces.md

If you want to delete tags by name, you can put all those into an array (or in my case, Dictionary - python). Then loop through your tags and use a conditional to look for the name and then pass the corresponding ID to the Delete Tag API call found on the tags page:

https://github.com/toggl/toggl_api_docs/blob/master/chapters/tags.md

Its a little frustrating I know, I've been coming up with all sorts of workarounds for this API. Hope this helps and if you can specify your use a little more I may be able to provide further insight.

**Comment by samuelkordik** [comment]
@zimmerel Thanks! This does seem to be the most promising angle to tackle this. My primary use case  is linking Omnifocus tasks and Toggl time entries; I am doing this by storing the Omnifocus task ID as a tag on the time entry and then removing it once completed.

I can see two ways forward: one is to use this method of finding the tag ID to delete it and another is to stop using the tag at all and maintain a cached key-value store linking the two IDs.

**Comment by zimmerel** [comment]
I hear your frustrations on that one! We use Asana and have been trying to setup an integration between the two. Toggl already has an integration setup, but we are finding a ton of hurdles along the way. Their integration doesn't store any of the project/task ID's and also can't grab all of our projects because they don't support pagination, so we've had to come up with our own.

Currently, we are throwing everything into a SQL database, where all the other data we have matches up smoothly with IDs, but our Asana projects and Toggl projects are only linked by name (which is fine as long as nobody changes the name, something that has happened before). Eventually, I'm looking to junk Toggl's built in integration and run the scripts myself, allowing me to grab the IDs from each and match them up nicely.

It seems like those two options that you listed are your best for now, unless you have use for putting them in some sort of database, where you can deposit the keys in each table. Which has it's uses for reporting, but I'm not sure what your needs are and how viable that is.

**Comment by joeriharleman** [comment]
Hello @samuelkordik!

Thank you for submitting your issue. Unfortunately this repository is largely unmaintained, which means issues remain unseen and do not get dealt with in a respectable manner. We're sorry for not getting back to you sooner.

This issue has been around for a long time so we will close it for now, but please let our excellent 24/5 support staff know you if you have any unresolved issues with our platform, documentation or APIs. They're also really good at noting down feature requests for our development teams. Please find them on our [support page](https://support.toggl.com/en/) by clicking the little icon in the bottom right corner of the screen.

Kind regards,
Joeri from Toggl
