### ISSUE TITLE
tag_ids=0 on detailed report does not filter response

### ISSUE THREAD

**Issue by J-Kelley** [toggl/toggl_api_docs#277]
Using the parameter tag_ids=0 on the detailed report returns records that have no tags.

**Comment by shedokan** [comment]
`tag_ids` is an array, so passing an integer is not the way to go.
I believe your'e looking for `tag_ids=[null]`

**Comment by shedokan** [comment]
I am sorry, I confused the endpoint, please provide the `X-Request-ID` you're getting

**Comment by J-Kelley** [comment]
Hi Shedokan,  I'm sorry but I'm actually completely new to the toggl api and not sure how to get that information.  Is there a link to it?

**Comment by shedokan** [comment]
Hi J-Kelley :)
The `X-Request-ID` is a header you get from the request's response.

**Comment by J-Kelley** [comment]
Thank you, I found it.  "e6304dfcb57f0221e7a6c3a4ee5bd293"

**Comment by shedokan** [comment]
Looks like you're not sending `tag_ids=0` as a GET param, it should be something like this:
`/reports/api/v2/details?user_agent=<USER_AGENT>&workspace_id=<WORKSPACE_ID>&since=<SINCE>&tag_ids=0`

If you have any issues, please contact our support team, with you full request and full response you're getting.

Cheers.

**Comment by J-Kelley** [comment]
As far as I can tell that's what I'm doing, though I had temporarily turned it off in my live code.  I may have sent a request id with it off by mistake.  Here is an updated request id:

ff8bdd791f2b64d9869a18aa6b03fd63

And this is the GET param directly from guzzle: 
/reports/api/v2/details?user_agent=<my email>&workspace_id=<my workspace id>&since=2017-08-13&tag_ids=0

Thank you.  If this should still go to the support team instead of here in issues please let me know and I'll send it over there.  Thank you.

**Comment by shedokan** [comment]
The preffered method is sending us an email to support@toggl.com, that's more appropriate than this public channel.

There you can send your full request and parameters exactly, without filtering out what might be important information to solving your issues, thank you.

**Comment by webervin** [comment]
I did recheck request ff8bdd791f2b64d9869a18aa6b03fd63 it did not return any time entries  with tags. Please provide details on what  was incorrect (like provide id of records that where  returned incorrectly) when writing to support. Best would be to include curl example like:
```
curl -v  -u FILTERED:api_token  "https://toggl.com/reports/api/v2/details?user_agent=FILTERED&workspace_id=XXXX&since=2017-08-13&tag_ids=0"
```
but with nothing filtered out (so that request and response can be seen).  Note that  you will be able to reset your api token in your profile (https://support.toggl.com/my-profile/#api)  after your support case is resolved.

**Comment by J-Kelley** [comment]
In case anyone is looking for the solution to this in the future, I received an answer back from toggl support.  The API documents themselves are a little misleading, tag_ids=0 returns all records without tags instead of removing all records without tags.

In order to return only records with tags you first must use the workspace tags api call to get a list of all the tags and then send the associated ids with tag_ids.

Thank you all for your help.
