### ISSUE TITLE
Doc on report API wrong about user name

### ISSUE THREAD

**Issue by oliver-gramberg** [toggl/toggl_api_docs#310]
Doc on report API says, "The API token is the user name and the string 'api_token' is the password." That seems not quite right.

**Comment by danielabbatt** [comment]
Yes I remember this being a bit odd, but this is how it works, whether it looks a bit funny or not ;)
Are you having trouble with it? 
The password of 'api_token' is just indicating to the API that the username is actually a token and not a username. I think it's this way round so that the username is always some kind of unique identifier, rather than the username being 'api_token' and the token being in the password field.

**Comment by webervin** [comment]
doc describes how it works in current api version.
